config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

  resource :user, only: :destroy do
    get 'retire'
  end

  resources :events, except: :index do
    resources :tickets, only: [:new, :create, :destroy]
  end

  match '*path' => 'application#error404', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :event_image, EventImageUploader

  has_many :tickets, dependent: :destroy
  belongs_to :owner, class_name: 'User'

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100}, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_time, presence: true
  validates :end_time,   presence: true
  validate :start_time_should_be_before_end_time

  def self.ransackable_attributes(auth_object = nil)
    %w(name start_time)
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  private

  def start_time_should_be_before_end_time
    return unless start_time && end_time

    if start_time >= end_time
      errors.add :start_time, I18n.t('message.error.start_time_should_be_before_end_time')
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :check_all_events_finished

  has_many :created_events, class_name: 'Event', foreign_key: :owner_id, dependent: :nullify
  has_many :tickets, dependent: :nullify
  has_many :participating_events, through: :tickets, source: :event

  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end

  private

  def check_all_events_finished
    now = Time.zone.now
    if created_events.where(':now < end_time', now: now).exists?
      errors[:base] << I18n.t('message.error.not_end_created_event_exists')
    end

    if participating_events.where(':now < end_time', now: now).exists?
      errors[:base] << I18n.t('message.error.not_end_joined_event_exists')
    end

    errors.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  # rescue_from Exception, with: :error500
  rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError, with: :error404

  def error404
    render :error404, status: 404, formats: [:html]
  end

  def error500(e)
    logger.error [e, *e.backtrace].join("\n")
    render :error500, status: 500, formats: [:html]
  end

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: t('message.alert.no_login')
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate, except: :show

  def show
    @event = Event.find(params[:id])
    @ticket = current_user && current_user.tickets.find_by(event_id: params[:id])
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: t('message.notice.created_event')
    else
      render :new
    end
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: t('message.notice.updated_event')
    else
      render :edit
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: t('message.notice.deleted_event')
  end

  private

  def event_params
    params.require(:event).permit(
      :name,
      :place,
      :event_image,
      :event_image_cache,
      :remove_event_image,
      :content,
      :start_time,
      :end_time
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_url, notice: 'ログインしました'
  end

  def destroy
    # reset_session
    session[:user_id] = nil
    redirect_to root_url, notice: 'ログアウトしました'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate

  def new
    raise ActionController::RoutingError, t('message.exception.invalid_tickets_new')
  end

  def create
    ticket = current_user.tickets.build do |t|
      t.event_id = params[:event_id]
      t.comment = params[:ticket][:comment]
    end
    if ticket.save
      flash[:notice] = t 'message.notice.joined_event'
      head 201
    else
      render json: { messages: ticket.errors.full_messages }, status: 422
    end
  end

  def destroy
    ticket = current_user.tickets.find_by!(event_id: params[:event_id])
    ticket.destroy!
    redirect_to event_path(params[:event_id]), notice: t('message.notice.canceled_event')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate

  def retire
  end

  def destroy
    if current_user.destroy
      reset_session
      redirect_to root_path, notice: t('message.notice.retired')
    else
      render :retire
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  PER = 3

  def index
    @q = Event.page(params[:page]).per(PER).order(:start_time).search(search_params)
    @events = @q.result(distinct: true)
  end

  private

  def search_params
    params.require(:q).permit(:name_cont, :start_time_gteq)
  rescue
    { start_time_gteq: Time.zone.now }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_for_twitter(user)
    "https://twitter.com/#{user.nickname}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/error404.html.slim
= t 'errors.error404'

app/views/application/error500.html.slim
= t 'errors.error500'

app/views/events/edit.html.slim
- now = Time.zone.now

.page-header
  h1 = t '.h1'

= form_for(@event, class: 'form-horizontal', role: 'form') do |f|
  - if @event.errors.any?
    .alert.alert-danger
      ul
        - @event.errors.full_messages.each do |msg|
          li = msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :place
    = f.text_field :place, class: 'form-control'

  .form-group
    - if @event.event_image?
      .thumnail
        = image_tag @event.event_image.url
    = f.file_field :event_image
    = f.hidden_field :event_image_cache

  - if @event.event_image?
    .checkbox
      label
        = f.check_box :remove_event_image
        = t '.remove_event_image'

  .form-group
    = f.label :start_time
    div = f.datetime_select :start_time, start_year: now.year, end_year: now.year + 1

  .form-group
    = f.label :end_time
    div = f.datetime_select :end_time, start_year: now.year, end_year: now.year + 1

  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control', row: 10

  = f.submit t('.update_button'), class: 'btn btn-default', data: { disable_with: t('.processing_msg') }

app/views/events/new.html.slim
- now = Time.zone.now

.page-header
  h1 = t '.h1'

= form_for(@event, class: 'form-horizontal', role: 'form') do |f|
  - if @event.errors.any?
    .alert.alert-danger
      ul
        - @event.errors.full_messages.each do |msg|
          li = msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :place
    = f.text_field :place, class: 'form-control'

  .form-group
    - if @event.event_image?
      .thumnail
        = image_tag @event.event_image.url
    = f.file_field :event_image
    = f.hidden_field :event_image_cache

  .form-group
    = f.label :start_time
    div = f.datetime_select :start_time, start_year: now.year, end_year: now.year + 1

  .form-group
    = f.label :end_time
    div = f.datetime_select :end_time, start_year: now.year, end_year: now.year + 1

  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control', row: 10

  = f.submit t('.create_button'), class: 'btn btn-default', data: { disable_with: t('.processing_msg') }

app/views/events/show.html.slim
.page-header
  h1 = @event.name

.row
  .col-md-8
    - if @event.event_image?
      .thumnail
        = image_tag @event.event_image.url
    .panel.panel-default
      .panel-heading = t '.owner'
      .panel-body
        - if @event.owner
          = link_to "https://twitter.com/#{@event.owner.nickname}"
            = image_tag @event.owner.image_url
            = "@#{@event.owner.nickname}"
        - else
          = t '.owner_retired_message'

    .panel.panel-default
      .panel-heading = t '.start_time'
      .panel-body = "#{@event.start_time.strftime('%Y/%m/%d %H:%M')} - #{@event.end_time.strftime('%Y/%m/%d %H:%M')}"

    .panel.panel-default
      .panel-heading = t '.place'
      .panel-body = @event.place

    .panel.panel-default
      .panel-heading = t '.content'
      .panel-body = @event.content

  .col-md-4
    - if @event.created_by? current_user
      = link_to t('.edit_button'), edit_event_path(@event), class: 'btn btn-info btn-lg btn-block'
      = link_to t('.delete_button'), event_path(@event), class: 'btn btn-danger btn-lg btn-block', method: :delete, data: { confirm: t('.delete_confirm') }
    - if @ticket
      = link_to t('.ticket.button.cancel'),
                event_ticket_path(@event, @ticket),
                method: :delete,
                class: 'btn btn-warning btn-lg btn-block',
                data: { confirm: t('.delete_confirm') }
    - elsif logged_in?
      button.btn.btn-primary.btn-lg.btn-block data-toggle="modal" data-target="#createTicket" = t '.ticket.button.join'
      #createTicket.modal.fade tabindex="-1" role="dialog" aria-labelledby="dialogHeader" aria-hidden="true"
        .modal-dialog
          .modal-content
            .modal-header
              button.close type="button" data-dismiss="modal" aria-hidden="true" &times;
              h4#dialogHeader.modal-title = t('.ticket.modal.title')
            = form_for @event.tickets.build, url: event_tickets_path(@event), remote: true do |f|
              .modal-body
                = f.text_field :comment, class: 'form-control'
              .modal-footer
                button.btn.btn-default type="button" data-dismiss="modal" = t('.ticket.modal.cancel')
                = f.button t('.ticket.modal.send'), class: 'btn btn-primary', data: { disable_with: t('.ticket.modal.sending') }
    - else
      = link_to t('.ticket.button.join'), new_event_ticket_path(@event), class: 'btn btn-primary btn-lg btn-block'
    hr
    .panel.panel-default
      .panel-heading = t '.joiner'
      .panel-body
        ul.list-unstyled
          - @tickets.each do |ticket|
            - if ticket.user
              li
                = link_to url_for_twitter(ticket.user) do
                  = image_tag ticket.user.image_url, width: 20, height: 20
                  = "@#{ticket.user.nickname}"
                = ticket.comment
            - else
              = t '.joiner_retired_message'

app/views/layouts/application.html.slim
DOCTYPE
html
  head
    title AwesomeEventsRails5
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    header.navbar.navbar-default role="navigation"
      .container
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'AwesomeEventsRails5', root_path, class: 'navbar-brand'
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          ul.nav.navbar-nav.navbar-right
            li = link_to t('header.create_event'), new_event_path
            - if logged_in?
              li = link_to t('header.retire'), retire_user_path
              li = link_to t('header.logout'), logout_path
            - else
              li = link_to t('header.twitter_login'), '/auth/twitter'
    .container
      - if flash[:notice]
        .alert.alert-success
          = flash[:notice]
      - if flash[:alert]
        .alert.alert-danger
          = flash[:alert]
      == yield

app/views/users/retire.html.slim
.page-header
  h1 = t '.h1'

- current_user.errors.any?
  .alert.alert-danger
    ul
      - current_user.errors.full_messages.each do |msg|
        li = msg

p = t '.alert1'
p = t '.alert2'

ul
  li = t '.conditions.no1'
  li = t '.conditions.no2'

hr

= link_to t('.button.retire'), user_path, method: :delete, class: 'btn btn-danger'

app/views/welcome/index.html.slim
- now = Time.zone.now

.page-header
  h1 = t '.h1'

= search_form_for @q, url: root_path, class: 'well' do |f|
  .form-group
    = f.label :name_cont, t('.search.conditions.event_name')
    = f.text_field :name_cont, class: 'form-control'
  .form-group
    = f.label :start_time_gteq, t('.search.conditions.start_time')
    div
      = f.date_select :start_time_gteq, start_year: now.year, end_year: now.year + 1, prompt: true
  = f.submit t('.search.submit'), class: 'btn btn-default'

.list-group
  - @events.each do |event|
    = link_to event, class: 'list-group-item' do
      h4.list-group-item-heading
        = event.name
      p.list-group-item-text
        = "#{event.start_time.strftime('%Y/%m/%d %H:%M')} - #{event.end_time.strftime('%Y/%m/%d %H:%M')}"
  = paginate @events